/** @type {import('tailwindcss').Config} */
// Design tokens lifted directly from the ImmerseOS visual language
// (dark "operating system" surface, blue/cyan atmospheric accents).
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './projection.html',
    './remote.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#00363d',
        'on-tertiary-fixed': '#07006c',
        primary: '#adc6ff',
        'surface-container': '#1e2024',
        'outline-variant': '#414755',
        'surface-container-low': '#1a1c20',
        'surface-container-high': '#282a2e',
        tertiary: '#c0c1ff',
        'on-primary-fixed': '#001a41',
        'secondary-fixed-dim': '#00daf3',
        'surface-dim': '#111317',
        secondary: '#bdf4ff',
        outline: '#8b90a0',
        'on-error': '#690005',
        'on-tertiary-container': '#0d0096',
        'on-background': '#e2e2e8',
        'primary-fixed': '#d8e2ff',
        'on-surface-variant': '#c1c6d7',
        'surface-container-lowest': '#0c0e12',
        'surface-tint': '#adc6ff',
        'on-surface': '#e2e2e8',
        'secondary-container': '#00e3fd',
        'inverse-primary': '#005bc1',
        'primary-container': '#4b8eff',
        surface: '#111317',
        'tertiary-container': '#8083ff',
        'surface-container-highest': '#333539',
        'inverse-on-surface': '#2f3035',
        error: '#ffb4ab',
        'on-primary-fixed-variant': '#004493',
        'error-container': '#93000a',
        'secondary-fixed': '#9cf0ff',
        'on-secondary-fixed-variant': '#004f58',
        'tertiary-fixed': '#e1e0ff',
        'inverse-surface': '#e2e2e8',
        'on-tertiary': '#1000a9',
        'on-secondary-fixed': '#001f24',
        'on-secondary-container': '#00616d',
        'primary-fixed-dim': '#adc6ff',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-error-container': '#ffdad6',
        'surface-bright': '#37393e',
        'on-primary-container': '#00285c',
        'surface-variant': '#333539',
        'on-primary': '#002e69',
        background: '#111317',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '40px',
        base: '8px',
        xl: '64px',
        md: '24px',
        xs: '4px',
        sm: '12px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '0.3', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(1.1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        'pulse-slow': 'pulse-slow 8s infinite ease-in-out',
        float: 'float 6s infinite ease-in-out',
      },
    },
  },
  plugins: [],
};
